FROM debian:buster

RUN		apt-get update && apt-get upgrade
RUN 	apt-get install -y mariadb-server

RUN mkdir /var/run/mysqld; \
    chmod 777 /var/run/mysqld;

COPY ./conf/my.conf /etc/mysql/my.conf

RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql

EXPOSE 3306

COPY ./tools/create_db.sh .
RUN sh create_db.sh && rm create_db.sh
USER mysql
CMD ["mysqld", "--skip-log-error"]